"use client";
import { useEffect, useRef, useState, type CSSProperties, type PointerEvent as ReactPointerEvent } from "react";
const projects = [
  { n:"01", title:"Boundaries from the record", type:"Research · Spatial analysis", tone:"rose", href:"", detail:"Reconstructing service-area boundaries from deeds, metes-and-bounds calls, and regulatory records—then finding the discrepancies that matter." },
  { n:"02", title:"Ordinances made navigable", type:"Web GIS · Information design", tone:"teal", href:"", detail:"Turning years of zoning documents into a secure, searchable map experience with clear popups, linked records, and a thoughtful handoff." },
  { n:"03", title:"A clean handoff across organizations", type:"ArcGIS Online · Systems thinking", tone:"plum", href:"", detail:"Untangling ownership, dependencies, vector tiles, and collaboration settings so a complex GIS application can move without breaking." },
  { n:"04", title:"Complexity made navigable", type:"Custom Web GIS · JSON configuration", tone:"sand", href:"/case-studies/custom-web-gis", detail:"Adapting a configuration-driven viewer to organize 51 layers, two basemap experiences, nested controls, and a public-facing legend without flattening the data." },
];
const gisSkills=["SPATIAL RESEARCH","SPATIAL ANALYSIS","CARTOGRAPHIC DESIGN","DATA STORYTELLING","ARCGIS PRO","WEB GIS","EXPERIENCE BUILDER","JSON CONFIGURATION","SANITY CMS","ARCADE","ATTRIBUTE RULES","HOSTED FEATURE LAYERS","VECTOR TILE PUBLISHING","DATA GOVERNANCE","ENTERPRISE GIS SYSTEMS"];
function HeroReveal(){
  const wrapRef=useRef<HTMLDivElement>(null);const svgRef=useRef<SVGSVGElement>(null);const lensRef=useRef<SVGCircleElement>(null);const haloRef=useRef<SVGCircleElement>(null);const activeRef=useRef(false);const visibleRef=useRef(true);const idleTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null);
  const place=(x:number,y:number)=>{lensRef.current?.setAttribute("cx",x.toFixed(1));lensRef.current?.setAttribute("cy",y.toFixed(1));haloRef.current?.setAttribute("cx",x.toFixed(1));haloRef.current?.setAttribute("cy",y.toFixed(1))};
  useEffect(()=>{let frame=0;const started=performance.now();const observer=new IntersectionObserver(([entry])=>{visibleRef.current=entry.isIntersecting},{rootMargin:"120px"});if(wrapRef.current)observer.observe(wrapRef.current);const drift=(now:number)=>{if(visibleRef.current&&document.visibilityState==="visible"&&!activeRef.current){const t=(now-started)/1000;const targetX=455+Math.sin(t*.34)*122+Math.sin(t*.13)*34;const targetY=278+Math.cos(t*.29)*112+Math.sin(t*.17)*26;const currentX=Number(lensRef.current?.getAttribute("cx"))||targetX;const currentY=Number(lensRef.current?.getAttribute("cy"))||targetY;place(currentX+(targetX-currentX)*.018,currentY+(targetY-currentY)*.018)}frame=requestAnimationFrame(drift)};frame=requestAnimationFrame(drift);return()=>{cancelAnimationFrame(frame);observer.disconnect();if(idleTimerRef.current)clearTimeout(idleTimerRef.current)}},[]);
  const holdForPointer=()=>{activeRef.current=true;if(idleTimerRef.current)clearTimeout(idleTimerRef.current);idleTimerRef.current=setTimeout(()=>{activeRef.current=false},2000)};
  const move=(event:ReactPointerEvent<HTMLDivElement>)=>{const svg=svgRef.current;if(!svg)return;const matrix=svg.getScreenCTM();if(!matrix)return;const point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const local=point.matrixTransform(matrix.inverse());holdForPointer();place(local.x,local.y)};
  const leave=()=>{if(idleTimerRef.current)clearTimeout(idleTimerRef.current);idleTimerRef.current=null;activeRef.current=false};
  return <div ref={wrapRef} className="hero-reveal" onPointerEnter={holdForPointer} onPointerMove={move} onPointerLeave={leave} aria-label="Move over the map to uncover its spatial layers">
    <svg ref={svgRef} viewBox="0 0 760 570" role="img" aria-labelledby="hero-reveal-title hero-reveal-desc">
      <title id="hero-reveal-title">A living landscape revealed through spatial data</title><desc id="hero-reveal-desc">A roaming field of clarity uncovers parcels, contours, utilities, drainage, a lake, and shoreline trees.</desc>
      <defs><radialGradient id="hero-reveal-gradient"><stop offset="0" stopColor="white" stopOpacity="1"/><stop offset=".48" stopColor="white" stopOpacity=".92"/><stop offset=".82" stopColor="white" stopOpacity=".2"/><stop offset="1" stopColor="black" stopOpacity="0"/></radialGradient><radialGradient id="hero-art-feather-gradient"><stop offset="0" stopColor="white" stopOpacity="1"/><stop offset=".58" stopColor="white" stopOpacity=".98"/><stop offset=".78" stopColor="white" stopOpacity=".62"/><stop offset="1" stopColor="black" stopOpacity="0"/></radialGradient><mask id="hero-reveal-mask"><rect width="760" height="570" fill="black"/><circle ref={lensRef} cx="530" cy="260" r="145" fill="url(#hero-reveal-gradient)"/></mask><mask id="hero-art-feather"><rect x="-20" y="-20" width="800" height="610" fill="url(#hero-art-feather-gradient)"/></mask></defs>
      <g mask="url(#hero-art-feather)"><image className="hero-map-image hero-map-image-ghost" href="/hero-gis-map-artwork-v1.webp" x="0" y="0" width="760" height="570" preserveAspectRatio="xMidYMid slice"/><image className="hero-map-image hero-map-image-detail" href="/hero-gis-map-artwork-v1.webp" x="0" y="0" width="760" height="570" preserveAspectRatio="xMidYMid slice" mask="url(#hero-reveal-mask)"/></g>
      <g className="hero-base-map"><path className="road" d="M35 441 C166 406 268 376 363 386 C479 398 576 455 744 502"/><path className="road" d="M194 18 C223 133 249 250 270 390 C283 468 291 520 298 558"/><path className="parcel-main" d="M276 115 L489 158 L538 372 L349 389 L273 319 Z"/><path d="M91 103 L216 72 L238 195 L121 216 Z M111 220 L240 198 L255 308 L135 333 Z M139 339 L258 314 L271 384 L165 407 Z"/><path d="M493 92 L642 118 L600 238 L512 210 Z M516 215 L600 242 L570 353 L538 370 Z M605 246 L722 275 L683 410 L572 356 Z"/><path className="lake-ghost" d="M570 158 C614 137 671 149 695 184 C716 215 698 248 661 263 C626 278 580 268 558 239 C536 210 539 174 570 158 Z"/></g>
      <g className="hero-detail-map" mask="url(#hero-reveal-mask)"><path className="road detail-road" d="M35 441 C166 406 268 376 363 386 C479 398 576 455 744 502"/><path className="road-edge" d="M31 430 C162 395 270 365 366 375 C486 387 582 444 748 491 M39 452 C169 417 266 387 360 397 C473 409 570 466 740 513"/><path className="road detail-road" d="M194 18 C223 133 249 250 270 390 C283 468 291 520 298 558"/><path className="road-edge" d="M183 20 C212 136 238 252 259 392 C272 469 280 521 287 560 M205 16 C234 130 260 248 281 388 C294 466 302 519 309 556"/>
        <g className="hero-contours"><path d="M313 153 C351 126 411 130 452 158 C489 183 504 227 486 256 C468 286 417 300 370 287 C326 275 300 238 304 201 C306 184 307 169 313 153"/><path d="M327 173 C358 151 405 153 438 175 C468 195 480 228 466 251 C451 275 411 284 374 274 C339 264 319 235 322 207 C323 193 323 183 327 173"/><path d="M345 194 C369 178 401 179 426 194 C449 208 458 231 447 248 C436 265 407 270 381 263 C355 256 341 236 343 216 C344 207 343 201 345 194"/><path d="M358 216 C375 205 397 205 414 215 C430 225 436 239 429 250 C421 261 402 264 385 259 C367 255 357 242 358 229 Z"/></g>
        <path className="parcel-main bright" d="M276 115 L489 158 L538 372 L349 389 L273 319 Z"/><path className="setback" d="M296 144 L468 179 L509 348 L363 362 L300 305 Z"/><path className="drainage" d="M326 163 C353 209 347 239 381 273 C411 304 427 323 448 357"/><path className="drainage" d="M453 181 C432 214 431 247 411 276 C390 305 372 326 365 354"/><path className="utility" d="M251 42 L267 112 L281 189 L286 259 L297 327 L315 389"/>
        <path className="lake" d="M570 158 C614 137 671 149 695 184 C716 215 698 248 661 263 C626 278 580 268 558 239 C536 210 539 174 570 158 Z"/><path className="shoreline" d="M565 150 C613 126 678 140 705 180 C730 218 706 258 665 275 C623 292 570 279 548 244 C524 207 530 170 565 150 Z"/>
        <g className="trees">{[[552,157],[580,139],[615,132],[650,138],[687,153],[708,181],[714,216],[698,250],[675,274],[642,285],[607,281],[573,263],[546,239],[538,205]].map(([x,y],i)=><g transform={`translate(${x} ${y})`} key={i}><circle r="8"/><circle cx="-6" cy="2" r="5"/><circle cx="6" cy="3" r="5"/><path d="M0 7 v8"/></g>)}</g>
        <g className="buildings"><path d="M132 132 h39 v31 h-39 Z M166 257 h44 v35 h-44 Z M182 348 h38 v28 h-38 Z"/><path d="M551 321 h46 v34 h-46 Z M628 302 h41 v38 h-41 Z M557 474 h49 v32 h-49 Z"/><path d="M361 432 h42 v31 h-42 Z M454 454 h39 v32 h-39 Z"/></g><g className="data-points"><circle cx="279" cy="187" r="3"/><circle cx="290" cy="258" r="3"/><circle cx="302" cy="329" r="3"/><circle cx="381" cy="273" r="3"/><circle cx="448" cy="357" r="3"/><circle cx="411" cy="276" r="3"/></g>
      </g><circle ref={haloRef} cx="530" cy="260" r="145" className="hero-lens-halo"/>
    </svg>
  </div>
}
export default function Home(){
  const layersRef=useRef<HTMLDivElement>(null); const perspectiveRef=useRef<HTMLDivElement>(null); const directionRef=useRef<HTMLElement>(null); const workRef=useRef<HTMLElement>(null); const introRef=useRef<HTMLElement>(null);
  const [skillIndex,setSkillIndex]=useState(0);
  const pointOfViewTitle="One site.\nMany perspectives.";
  const [typedPointOfView,setTypedPointOfView]=useState("");
  const [pointOfViewDeckVisible,setPointOfViewDeckVisible]=useState(false);
  const [cardsVisible,setCardsVisible]=useState(false);
  useEffect(()=>{
    const onScroll=()=>{if(introRef.current){const r=introRef.current.getBoundingClientRect();const p=Math.max(0,Math.min(1,(innerHeight-r.top)/(innerHeight+r.height*.72)));const phase=(start:number,length:number)=>Math.max(0,Math.min(1,(p-start)/length));introRef.current.style.setProperty("--terrain-p",`${p}`);introRef.current.style.setProperty("--line-p",`${phase(.08,.25)}`);introRef.current.style.setProperty("--body-p",`${phase(.3,.18)}`);introRef.current.style.setProperty("--relief-p",`${phase(.48,.34)}`);introRef.current.style.setProperty("--mist-p",`${phase(.36,.46)}`)}if(directionRef.current){const r=directionRef.current.getBoundingClientRect();const travel=Math.max(900,r.height-innerHeight*.7);const p=Math.max(0,Math.min(1,(innerHeight*.72-r.top)/travel));const phase=(start:number,length:number)=>Math.max(0,Math.min(1,(p-start)/length));directionRef.current.style.setProperty("--path-p",`${p}`);directionRef.current.style.setProperty("--route-shift",`${p*190}px`);directionRef.current.style.setProperty("--intro-1",`${phase(0,.07)}`);directionRef.current.style.setProperty("--intro-2",`${phase(.045,.07)}`);directionRef.current.style.setProperty("--intro-3",`${phase(.09,.07)}`);directionRef.current.style.setProperty("--intro-4",`${phase(.14,.09)}`);directionRef.current.style.setProperty("--stage-1",`${phase(.21,.13)}`);directionRef.current.style.setProperty("--stage-2",`${phase(.39,.13)}`);directionRef.current.style.setProperty("--stage-3",`${phase(.57,.13)}`);directionRef.current.style.setProperty("--stage-4",`${phase(.76,.15)}`);directionRef.current.style.setProperty("--handoff-p",`${phase(.9,.1)}`)}if(workRef.current){const r=workRef.current.getBoundingClientRect();const phase=(start:number,length:number)=>Math.max(0,Math.min(1,((innerHeight*.86-r.top)/520-start)/length));workRef.current.style.setProperty("--work-1",`${phase(0,.24)}`);workRef.current.style.setProperty("--work-2",`${phase(.18,.24)}`);workRef.current.style.setProperty("--work-3",`${phase(.36,.24)}`)}};
    const reveals=[...document.querySelectorAll<HTMLElement>(".motion-reveal")];
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.14,rootMargin:"0px 0px -8%"});
    const terrainObserver=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle("terrain-active",entry.isIntersecting)),{threshold:.25});
    let ticking=false;const requestScroll=()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{onScroll();ticking=false})};
    reveals.forEach(el=>observer.observe(el));if(introRef.current)terrainObserver.observe(introRef.current);onScroll();addEventListener("scroll",requestScroll,{passive:true});
    return()=>{removeEventListener("scroll",requestScroll);observer.disconnect();terrainObserver.disconnect()}
  },[]);
  useEffect(()=>{const section=layersRef.current;if(!section)return;let typeTimer:ReturnType<typeof setInterval>|undefined;let startTimer:ReturnType<typeof setTimeout>|undefined;let deckTimer:ReturnType<typeof setTimeout>|undefined;let running=false;const stop=()=>{if(typeTimer)clearInterval(typeTimer);if(startTimer)clearTimeout(startTimer);if(deckTimer)clearTimeout(deckTimer);typeTimer=startTimer=deckTimer=undefined};const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting&&!running){running=true;stop();setTypedPointOfView("");setPointOfViewDeckVisible(false);startTimer=setTimeout(()=>{deckTimer=setTimeout(()=>setPointOfViewDeckVisible(true),1300);let i=0;typeTimer=setInterval(()=>{i+=1;setTypedPointOfView(pointOfViewTitle.slice(0,i));if(i===pointOfViewTitle.length){if(typeTimer)clearInterval(typeTimer);typeTimer=undefined}},88)},320)}else if(!entry.isIntersecting){running=false;stop();setTypedPointOfView("");setPointOfViewDeckVisible(false)}},{threshold:.12,rootMargin:"0px 0px -8%"});observer.observe(section);return()=>{observer.disconnect();stop()}},[]);
  useEffect(()=>{const grid=perspectiveRef.current;if(!grid)return;let timer:ReturnType<typeof setTimeout>|undefined;const entranceObserver=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){if(timer)clearTimeout(timer);timer=setTimeout(()=>setCardsVisible(true),100)}},{threshold:.01,rootMargin:"-55% 0px -30% 0px"});const resetObserver=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting){if(timer)clearTimeout(timer);setCardsVisible(false)}},{threshold:0,rootMargin:"0px"});entranceObserver.observe(grid);resetObserver.observe(grid);return()=>{entranceObserver.disconnect();resetObserver.disconnect();if(timer)clearTimeout(timer)}},[]);
  useEffect(()=>{const timer=setInterval(()=>setSkillIndex(index=>(index+1)%gisSkills.length),1000);return()=>clearInterval(timer)},[]);
  const skillStyle=(index:number)=>{const half=(gisSkills.length-1)/2;const slot=(index-skillIndex+half+gisSkills.length)%gisSkills.length;const positionAngle=-90+slot*(180/(gisSkills.length-1));const centered=(slot-half)/half;const depth=Math.max(0,Math.cos(centered*Math.PI/2));const radians=positionAngle*Math.PI/180;return{"--roll-angle":`${positionAngle}deg`,"--roll-x":`${Math.cos(radians)*250}px`,"--roll-y":`${Math.sin(radians)*350}px`,"--roll-o":`${.08+depth*.92}`,"--roll-blur":`${(1-depth)*5}px`,"--roll-scale":`${.72+depth*.28}`} as CSSProperties};
  return <main>
    <nav className="nav"><a className="mark" href="#top" aria-label="Home">YC<span>°</span></a><div><a href="#work">Work</a><a href="/workflows">Library</a><a href="#about">About</a><a href="/resume">Résumé</a><a href="#contact">Contact</a></div></nav>
    <section id="top" className="hero"><div className="grain"/><HeroReveal/><p className="eyebrow">GIS ANALYST · GISP · DALLAS, TEXAS</p><h1>Uncovering the narrative<br/>in spatial data.</h1><div className="hero-bottom"><p>I have fun turning spatial questions, tangled records, and complex systems into tools people can understand and use.<span className="hero-love">I love my job.</span></p><a href="#work" className="round-link">Explore work <span>↓</span></a></div></section>
    <section className="intro terrain-intro" id="about" ref={introRef}><div className="skills-roll-stage" aria-label="GIS skills"><div className="skills-roll">{gisSkills.map((skill,i)=><span key={skill} className={i===skillIndex?"is-current":""} style={skillStyle(i)}>{skill}</span>)}</div><i className="skills-roll-marker"/></div><div><h2>Maps are not the finish line.</h2><p className="lede">The real work is figuring out what the information means, how the pieces connect, and how to build something dependable from all of it.</p><p>I work where spatial research, technical problem-solving, and clear communication meet. I’m especially drawn to the systems behind the map: publishing, permissions, dependencies, governance, and the quiet architecture that keeps GIS useful.</p></div></section>
    <section className="layers viewpoint-section" ref={layersRef}>
      <div className="viewpoint-intro"><div className="layers-copy"><h2 className="typed-heading" aria-label={pointOfViewTitle}>{typedPointOfView}</h2><p className={`viewpoint-deck ${pointOfViewDeckVisible?"is-visible":""}`}><em>“The map is not the territory.”</em> The same site can produce different maps because the right answer depends on who’s asking. Explore how civil engineering, transportation, municipal responsibility, and public understanding reshape what the parcel means.</p></div><div className={`site-map parcel-image ${pointOfViewDeckVisible?"is-visible":""}`}><img src="/parcel-pencil-transparent-v1.webp" loading="lazy" decoding="async" alt="Pencil-blueprint parcel map with shaded roads and buildings surrounding a plum site"/></div></div>
      <div ref={perspectiveRef} className={`perspective-grid ${cardsVisible?"is-visible":""}`}>{[
        ["01","CIVIL","What can physically work here?","Contours, drainage, utilities, easements, and the net developable area shape what the site can support.","civil","site-feasibility"],
        ["02","TRANSPORTATION","How will people reach it?","Access points, right-of-way, turning movements, sidewalks, and pedestrian routes connect the parcel to everything around it.","transportation","corridor-impact"],
        ["03","MUNICIPALITY","What is allowed—and who is responsible?","Zoning, setbacks, jurisdiction, permits, and infrastructure ownership define the rules and the responsible parties.","municipality","ordinances-to-gis"],
        ["04","PUBLIC","What does this mean for me?","Technical layers resolve into clear streets, nearby places, likely change, and an answer someone can understand and use.","public","public-facing-web-gis"]
      ].map(x=><a className={`perspective-card ${x[4]}`} href={`/workflows/${x[5]}`} key={x[0]}><div className="perspective-label"><h3>{x[1]}</h3><p>{x[2]}</p></div><div className="perspective-answer"><p>{x[3]}</p><small>Read the workflow ↗</small></div></a>)}</div>
    </section>
    <section className="direction career-path" ref={directionRef} aria-labelledby="career-path-title">
      <div className="career-path-head"><p className="career-kicker">HOW MY WORK HAS EVOLVED</p><h2 id="career-path-title" className="career-ladder-title"><span>My career</span><span>didn’t start</span><span>with systems.</span></h2><div className="career-ladder-copy"><p>I first used GIS to study what was happening beneath and across the landscape:</p><p>from landfill volumes and subsidence,</p><p>to terrain, LiDAR, and spatial patterns.</p><p>Each role brought me further behind the finished map: into the data, the workflows, the publishing, and eventually the systems connecting it all.</p></div></div>
      <div className="career-route" aria-label="Career progression from scientific analysis to GIS systems">
        <svg className="career-line career-line-base" viewBox="0 0 1000 1880" preserveAspectRatio="none" aria-hidden="true"><path d="M500 20 C500 150 300 180 300 330 S710 460 710 650 S260 830 260 1020 S735 1190 735 1390 S500 1560 500 1840"/></svg>
        <div className="career-line-reveal" aria-hidden="true"><svg className="career-line" viewBox="0 0 1000 1880" preserveAspectRatio="none"><path className="career-line-progress" d="M500 20 C500 150 300 180 300 330 S710 460 710 650 S260 830 260 1020 S735 1190 735 1390 S500 1560 500 1840"/></svg></div>
        <div className="career-stages">
          <article className="career-stage stage-one"><span>01 · SCIENTIFIC FOUNDATIONS</span><h3>Geosciences, remote sensing &amp; spatial analysis</h3><p>GPS-based volumetric calculations, seismic-reflection research, LiDAR and terrain data, remote sensing, data mining, machine learning, and published web maps.</p><div><i>GPS</i><i>LiDAR</i><i>Remote sensing</i><i>Spatial analysis</i></div></article>
          <article className="career-stage stage-two"><span>02 · BUILDING DEPENDABLE GIS DATA</span><h3>Production, automation &amp; documentation</h3><p>Geodatabases, cartographic deliverables, automated data collection, data integration, database models, metadata, requirements, workflows, and conversion specifications.</p><div><i>Geodatabases</i><i>Automation</i><i>Metadata</i><i>Data integration</i></div></article>
          <article className="career-stage stage-three"><span>03 · DELIVERING CONNECTED GIS TOOLS</span><h3>Web GIS, configuration &amp; technical problem-solving</h3><p>ArcGIS Online, Experience Builder, configuration-driven web maps, JSON, Sanity, hosted layers, vector tiles, Arcade, Azure-hosted records, permissions, application dependencies, collaboration, and technical handoffs.</p><div><i>ArcGIS Online</i><i>Experience Builder</i><i>JSON + Sanity</i><i>Vector tiles</i></div></article>
          <article className="career-stage stage-four"><span>CURRENT DIRECTION</span><h3>GIS systems &amp; technical ownership</h3><p>I’m growing beyond individual deliverables and into the environments connecting them: Portal, ArcGIS Enterprise, Azure, integrations, governance, troubleshooting, and the documentation that makes a system dependable.</p><div><i>Portal</i><i>ArcGIS Enterprise</i><i>Integrations</i><i>Governance</i></div></article>
        </div>
      </div>
      <div className="career-handoff" aria-hidden="true"><i className="career-handoff-line"/><span className="career-handoff-arrow">↓</span></div>
    </section>
    <section id="work" className="work" ref={workRef}><div className="work-head"><h2 className="work-story-title"><span>Along the way,</span><span>I’ve helped untangle</span><span>a few problems.</span></h2></div><div className="project-grid">{projects.map(p=>p.href?<a className={`project ${p.tone}`} href={p.href} key={p.n}><div className="map-art" aria-hidden="true"><i/><i/><i/><b/><span/></div><div className="project-title"><span>{p.n}</span><h3>{p.title}</h3><p>{p.type}</p></div><div className="project-reveal"><p>{p.detail}</p><span>View case study ↗</span></div></a>:<article className={`project ${p.tone}`} key={p.n} tabIndex={0}><div className="map-art" aria-hidden="true"><i/><i/><i/><b/><span/></div><div className="project-title"><span>{p.n}</span><h3>{p.title}</h3><p>{p.type}</p></div><div className="project-reveal"><p>{p.detail}</p><span>Case study in development</span></div></article>)}</div><div className="work-library-cta"><p>More work lives beyond the highlights.</p><a href="/workflows">Explore the Work Library <span>↗</span></a></div></section>
    <footer id="contact"><p>Have a spatial question<br/>worth following?</p><a href="mailto:yxcastillo@gmail.com">Let’s map it out ↗</a><div><span>Yaneth Castillo, GISP</span><span>© 2026</span></div></footer>
  </main>
}
