export type Workflow = {
  slug:string; number:string; lens:string; title:string; question:string; intro:string;
  matters:string; layers:string[]; steps:{title:string;copy:string}[]; tools:string[];
  communicates:string; failure:string; applications:string[]; tone:string;
};

export const workflows:Workflow[]=[
  {slug:"site-feasibility",number:"01",lens:"Civil",title:"Finding what can physically work",question:"What can this site actually support?",intro:"A parcel boundary is only the beginning. A useful feasibility map brings together the physical and legal constraints that reduce a site to its genuinely workable area.",matters:"Civil decisions depend on relationships between layers—not on any single dataset. The workflow is about resolving those relationships clearly enough that the next person can make a defensible decision.",layers:["Contours and terrain","Drainage and flood information","Utilities and easements","Setbacks and parcel limits","Net developable area"],steps:[{title:"Establish the site",copy:"Confirm the parcel, coordinate system, source dates, and the question the map needs to answer."},{title:"Assemble constraints",copy:"Gather terrain, drainage, utilities, easements, setbacks, access, and other controlling information."},{title:"Normalize the evidence",copy:"Reproject, clip, document, and compare sources so that unlike datasets can be evaluated together."},{title:"Resolve relationships",copy:"Identify overlaps, gaps, conflicts, and the portions of the site that remain realistically usable."},{title:"Communicate the result",copy:"Build a map that shows both the conclusion and the evidence needed to understand it."}],tools:["ArcGIS Pro","Spatial analysis","Geodatabases","LiDAR","Cartographic design"],communicates:"Where development appears feasible, which constraints control the answer, and what still requires confirmation.",failure:"Treating every source as equally current or authoritative can produce a precise-looking answer that is still wrong. Dates, provenance, jurisdiction, and scale matter.",applications:["Site constraint exhibits","Utility planning","Drainage review","Preliminary development analysis"],tone:"rose"},
  {slug:"public-facing-web-gis",number:"04",lens:"Public",title:"Designing a map people can understand",question:"What does this technical information mean for me?",intro:"Public-facing GIS has a different finish line. Accuracy is essential, but the experience also has to translate specialist language into recognizable places, likely changes, and clear next steps.",matters:"A user should not need to understand layer names, database fields, or agency structure before the map becomes useful. Information design decides what appears first and what remains available for deeper inspection.",layers:["Plain-language labels","Recognizable landmarks","Layer hierarchy","Popup content","Responsive interaction"],steps:[{title:"Start with the user question",copy:"Define the decision or understanding the visitor should leave with—not merely the data available to display."},{title:"Build a visual hierarchy",copy:"Prioritize the site, nearby context, and the few layers that directly support the answer."},{title:"Translate the attributes",copy:"Replace internal codes and field names with concise labels, explanations, and links to the source record."},{title:"Design the interaction",copy:"Make hover, click, search, legend, and mobile behavior support the same clear reading path."},{title:"Test for interpretation",copy:"Check whether someone unfamiliar with the project can explain what the map means after using it."}],tools:["Experience Builder","ArcGIS Online","Popup design","Cartography","Information design"],communicates:"Where the subject is, why it matters, what may change, and where the user can verify or learn more.",failure:"Adding every available layer and field can make a technically complete application less understandable—and therefore less useful.",applications:["Public information viewers","Project story maps","Development context tools","Client-facing web maps"],tone:"plum"}
];

export const workflowBySlug=(slug:string)=>workflows.find(item=>item.slug===slug);
